var topics =
[
    [ "LSM6DSOX_Timestamp", "group__LSM6DSOX__Timestamp.html", "group__LSM6DSOX__Timestamp" ],
    [ "output", "group__LSM6DSOX__Data.html", "group__LSM6DSOX__Data" ],
    [ "LSM6DSOX_common", "group__LSM6DSOX__common.html", "group__LSM6DSOX__common" ],
    [ "LSM6DSOX_filters", "group__LSM6DSOX__filters.html", "group__LSM6DSOX__filters" ],
    [ "Auxiliary_interface", "group__LSM6DSOX__.html", "group__LSM6DSOX__" ],
    [ "LSM6DSOX_interrupt_pins", "group__LSM6DSOX__interrupt__pins.html", "group__LSM6DSOX__interrupt__pins" ],
    [ "LSM6DSOX_Wake_Up_event", "group__LSM6DSOX__Wake__Up__event.html", "group__LSM6DSOX__Wake__Up__event" ],
    [ "LSM6DSOX_tap_generator", "group__LSM6DSOX__tap__generator.html", "group__LSM6DSOX__tap__generator" ],
    [ "LSM6DSOX_free_fall", "group__LSM6DSOX__free__fall.html", "group__LSM6DSOX__free__fall" ],
    [ "LSM6DSOX_fifo", "group__LSM6DSOX__fifo.html", "group__LSM6DSOX__fifo" ],
    [ "LSM6DSOX_DEN_functionality", "group__LSM6DSOX__DEN__functionality.html", "group__LSM6DSOX__DEN__functionality" ],
    [ "LSM6DSOX_Pedometer", "group__LSM6DSOX__Pedometer.html", "group__LSM6DSOX__Pedometer" ],
    [ "LSM6DSOX_significant_motion", "group__LSM6DSOX__significant__motion.html", "group__LSM6DSOX__significant__motion" ],
    [ "LSM6DSOX_tilt_detection", "group__LSM6DSOX__tilt__detection.html", "group__LSM6DSOX__tilt__detection" ],
    [ "LSM6DSOX_finite_state_machine", "group__LSM6DSOX__finite__state__machine.html", "group__LSM6DSOX__finite__state__machine" ],
    [ "LSM6DSOX_Sensor_hub", "group__LSM6DSOX__Sensor__hub.html", "group__LSM6DSOX__Sensor__hub" ],
    [ "configuration", "group__Basic.html", "group__Basic" ],
    [ "BSP", "group__BSP.html", "group__BSP" ],
    [ "CMSIS Global Defines", "group__CMSIS__glob__defs.html", null ],
    [ "Defines and Type Definitions", "group__CMSIS__core__register.html", "group__CMSIS__core__register" ],
    [ "HAL CRYP Aliased Defines maintained for legacy purpose", "group__HAL__AES__Aliased__Defines.html", "group__HAL__AES__Aliased__Defines" ],
    [ "HAL ADC Aliased Defines maintained for legacy purpose", "group__HAL__ADC__Aliased__Defines.html", "group__HAL__ADC__Aliased__Defines" ],
    [ "HAL CEC Aliased Defines maintained for legacy purpose", "group__HAL__CEC__Aliased__Defines.html", "group__HAL__CEC__Aliased__Defines" ],
    [ "HAL COMP Aliased Defines maintained for legacy purpose", "group__HAL__COMP__Aliased__Defines.html", "group__HAL__COMP__Aliased__Defines" ],
    [ "HAL CORTEX Aliased Defines maintained for legacy purpose", "group__HAL__CORTEX__Aliased__Defines.html", "group__HAL__CORTEX__Aliased__Defines" ],
    [ "CRC API aliases", "group__CRC__Aliases.html", "group__CRC__Aliases" ],
    [ "HAL CRC Aliased Defines maintained for legacy purpose", "group__HAL__CRC__Aliased__Defines.html", "group__HAL__CRC__Aliased__Defines" ],
    [ "HAL DAC Aliased Defines maintained for legacy purpose", "group__HAL__DAC__Aliased__Defines.html", "group__HAL__DAC__Aliased__Defines" ],
    [ "HAL DMA Aliased Defines maintained for legacy purpose", "group__HAL__DMA__Aliased__Defines.html", "group__HAL__DMA__Aliased__Defines" ],
    [ "HAL FLASH Aliased Defines maintained for legacy purpose", "group__HAL__FLASH__Aliased__Defines.html", "group__HAL__FLASH__Aliased__Defines" ],
    [ "HAL JPEG Aliased Macros maintained for legacy purpose", "group__HAL__JPEG__Aliased__Macros.html", null ],
    [ "HAL SYSCFG Aliased Defines maintained for legacy purpose", "group__HAL__SYSCFG__Aliased__Defines.html", "group__HAL__SYSCFG__Aliased__Defines" ],
    [ "LL FMC Aliased Defines maintained for compatibility purpose", "group__LL__FMC__Aliased__Defines.html", null ],
    [ "LL FSMC Aliased Defines maintained for legacy purpose", "group__LL__FSMC__Aliased__Defines.html", "group__LL__FSMC__Aliased__Defines" ],
    [ "HAL GPIO Aliased Macros maintained for legacy purpose", "group__HAL__GPIO__Aliased__Macros.html", "group__HAL__GPIO__Aliased__Macros" ],
    [ "HAL GTZC Aliased Defines maintained for legacy purpose", "group__HAL__GTZC__Aliased__Defines.html", null ],
    [ "HAL HRTIM Aliased Macros maintained for legacy purpose", "group__HAL__HRTIM__Aliased__Macros.html", "group__HAL__HRTIM__Aliased__Macros" ],
    [ "HAL I2C Aliased Defines maintained for legacy purpose", "group__HAL__I2C__Aliased__Defines.html", "group__HAL__I2C__Aliased__Defines" ],
    [ "HAL IRDA Aliased Defines maintained for legacy purpose", "group__HAL__IRDA__Aliased__Defines.html", "group__HAL__IRDA__Aliased__Defines" ],
    [ "HAL IWDG Aliased Defines maintained for legacy purpose", "group__HAL__IWDG__Aliased__Defines.html", "group__HAL__IWDG__Aliased__Defines" ],
    [ "HAL LPTIM Aliased Defines maintained for legacy purpose", "group__HAL__LPTIM__Aliased__Defines.html", "group__HAL__LPTIM__Aliased__Defines" ],
    [ "HAL NAND Aliased Defines maintained for legacy purpose", "group__HAL__NAND__Aliased__Defines.html", "group__HAL__NAND__Aliased__Defines" ],
    [ "HAL NOR Aliased Defines maintained for legacy purpose", "group__HAL__NOR__Aliased__Defines.html", "group__HAL__NOR__Aliased__Defines" ],
    [ "HAL OPAMP Aliased Defines maintained for legacy purpose", "group__HAL__OPAMP__Aliased__Defines.html", "group__HAL__OPAMP__Aliased__Defines" ],
    [ "HAL I2S Aliased Defines maintained for legacy purpose", "group__HAL__I2S__Aliased__Defines.html", "group__HAL__I2S__Aliased__Defines" ],
    [ "HAL PCCARD Aliased Defines maintained for legacy purpose", "group__HAL__PCCARD__Aliased__Defines.html", "group__HAL__PCCARD__Aliased__Defines" ],
    [ "HAL RTC Aliased Defines maintained for legacy purpose", "group__HAL__RTC__Aliased__Defines.html", "group__HAL__RTC__Aliased__Defines" ],
    [ "HAL SMARTCARD Aliased Defines maintained for legacy purpose", "group__HAL__SMARTCARD__Aliased__Defines.html", "group__HAL__SMARTCARD__Aliased__Defines" ],
    [ "HAL SMBUS Aliased Defines maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Defines.html", "group__HAL__SMBUS__Aliased__Defines" ],
    [ "HAL SPI Aliased Defines maintained for legacy purpose", "group__HAL__SPI__Aliased__Defines.html", "group__HAL__SPI__Aliased__Defines" ],
    [ "HAL TIM Aliased Defines maintained for legacy purpose", "group__HAL__TIM__Aliased__Defines.html", "group__HAL__TIM__Aliased__Defines" ],
    [ "HAL TSC Aliased Defines maintained for legacy purpose", "group__HAL__TSC__Aliased__Defines.html", "group__HAL__TSC__Aliased__Defines" ],
    [ "HAL UART Aliased Defines maintained for legacy purpose", "group__HAL__UART__Aliased__Defines.html", "group__HAL__UART__Aliased__Defines" ],
    [ "HAL USART Aliased Defines maintained for legacy purpose", "group__HAL__USART__Aliased__Defines.html", "group__HAL__USART__Aliased__Defines" ],
    [ "HAL WWDG Aliased Defines maintained for legacy purpose", "group__HAL__WWDG__Aliased__Defines.html", "group__HAL__WWDG__Aliased__Defines" ],
    [ "HAL CAN Aliased Defines maintained for legacy purpose", "group__HAL__CAN__Aliased__Defines.html", "group__HAL__CAN__Aliased__Defines" ],
    [ "HAL ETH Aliased Defines maintained for legacy purpose", "group__HAL__ETH__Aliased__Defines.html", "group__HAL__ETH__Aliased__Defines" ],
    [ "HAL DCMI Aliased Defines maintained for legacy purpose", "group__HAL__DCMI__Aliased__Defines.html", "group__HAL__DCMI__Aliased__Defines" ],
    [ "HAL PPP Aliased Defines maintained for legacy purpose", "group__HAL__PPP__Aliased__Defines.html", null ],
    [ "HAL CRYP Aliased Functions maintained for legacy purpose", "group__HAL__CRYP__Aliased__Functions.html", "group__HAL__CRYP__Aliased__Functions" ],
    [ "HAL DCACHE Aliased Functions maintained for legacy purpose", "group__HAL__DCACHE__Aliased__Functions.html", null ],
    [ "HASH API alias", "group__HASH__alias.html", "group__HASH__alias" ],
    [ "HAL HASH Aliased Functions maintained for legacy purpose", "group__HAL__HASH__Aliased__Functions.html", "group__HAL__HASH__Aliased__Functions" ],
    [ "HAL Generic Aliased Functions maintained for legacy purpose", "group__HAL__Aliased__Functions.html", "group__HAL__Aliased__Functions" ],
    [ "HAL FLASH Aliased Functions maintained for legacy purpose", "group__HAL__FLASH__Aliased__Functions.html", "group__HAL__FLASH__Aliased__Functions" ],
    [ "HAL I2C Aliased Functions maintained for legacy purpose", "group__HAL__I2C__Aliased__Functions.html", "group__HAL__I2C__Aliased__Functions" ],
    [ "HAL PWR Aliased maintained for legacy purpose", "group__HAL__PWR__Aliased.html", "group__HAL__PWR__Aliased" ],
    [ "HAL SMBUS Aliased Functions maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Functions.html", "group__HAL__SMBUS__Aliased__Functions" ],
    [ "HAL SPI Aliased Functions maintained for legacy purpose", "group__HAL__SPI__Aliased__Functions.html", "group__HAL__SPI__Aliased__Functions" ],
    [ "HAL TIM Aliased Functions maintained for legacy purpose", "group__HAL__TIM__Aliased__Functions.html", "group__HAL__TIM__Aliased__Functions" ],
    [ "HAL UART Aliased Functions maintained for legacy purpose", "group__HAL__UART__Aliased__Functions.html", "group__HAL__UART__Aliased__Functions" ],
    [ "HAL LTDC Aliased Functions maintained for legacy purpose", "group__HAL__LTDC__Aliased__Functions.html", "group__HAL__LTDC__Aliased__Functions" ],
    [ "HAL PPP Aliased Functions maintained for legacy purpose", "group__HAL__PPP__Aliased__Functions.html", null ],
    [ "HAL CRYP Aliased Macros maintained for legacy purpose", "group__HAL__AES__Aliased__Macros.html", "group__HAL__AES__Aliased__Macros" ],
    [ "HAL Generic Aliased Macros maintained for legacy purpose", "group__HAL__Aliased__Macros.html", "group__HAL__Aliased__Macros" ],
    [ "HAL ADC Aliased Macros maintained for legacy purpose", "group__HAL__ADC__Aliased__Macros.html", "group__HAL__ADC__Aliased__Macros" ],
    [ "HAL DAC Aliased Macros maintained for legacy purpose", "group__HAL__DAC__Aliased__Macros.html", "group__HAL__DAC__Aliased__Macros" ],
    [ "HAL DBGMCU Aliased Macros maintained for legacy purpose", "group__HAL__DBGMCU__Aliased__Macros.html", "group__HAL__DBGMCU__Aliased__Macros" ],
    [ "HAL COMP Aliased Macros maintained for legacy purpose", "group__HAL__COMP__Aliased__Macros.html", "group__HAL__COMP__Aliased__Macros" ],
    [ "HAL FLASH Aliased Macros maintained for legacy purpose", "group__HAL__FLASH__Aliased__Macros.html", "group__HAL__FLASH__Aliased__Macros" ],
    [ "HAL I2C Aliased Macros maintained for legacy purpose", "group__HAL__I2C__Aliased__Macros.html", "group__HAL__I2C__Aliased__Macros" ],
    [ "HAL I2S Aliased Macros maintained for legacy purpose", "group__HAL__I2S__Aliased__Macros.html", "group__HAL__I2S__Aliased__Macros" ],
    [ "HAL IRDA Aliased Macros maintained for legacy purpose", "group__HAL__IRDA__Aliased__Macros.html", "group__HAL__IRDA__Aliased__Macros" ],
    [ "HAL IWDG Aliased Macros maintained for legacy purpose", "group__HAL__IWDG__Aliased__Macros.html", "group__HAL__IWDG__Aliased__Macros" ],
    [ "HAL LPTIM Aliased Macros maintained for legacy purpose", "group__HAL__LPTIM__Aliased__Macros.html", "group__HAL__LPTIM__Aliased__Macros" ],
    [ "HAL OPAMP Aliased Macros maintained for legacy purpose", "group__HAL__OPAMP__Aliased__Macros.html", "group__HAL__OPAMP__Aliased__Macros" ],
    [ "HAL PWR Aliased Macros maintained for legacy purpose", "group__HAL__PWR__Aliased__Macros.html", "group__HAL__PWR__Aliased__Macros" ],
    [ "HAL RCC Aliased maintained for legacy purpose", "group__HAL__RCC__Aliased.html", "group__HAL__RCC__Aliased" ],
    [ "HAL RNG Aliased Macros maintained for legacy purpose", "group__HAL__RNG__Aliased__Macros.html", "group__HAL__RNG__Aliased__Macros" ],
    [ "HAL RTC Aliased Macros maintained for legacy purpose", "group__HAL__RTC__Aliased__Macros.html", "group__HAL__RTC__Aliased__Macros" ],
    [ "HAL SD/MMC Aliased Macros maintained for legacy purpose", "group__HAL__SD__Aliased__Macros.html", "group__HAL__SD__Aliased__Macros" ],
    [ "HAL SMARTCARD Aliased Macros maintained for legacy purpose", "group__HAL__SMARTCARD__Aliased__Macros.html", "group__HAL__SMARTCARD__Aliased__Macros" ],
    [ "HAL SMBUS Aliased Macros maintained for legacy purpose", "group__HAL__SMBUS__Aliased__Macros.html", "group__HAL__SMBUS__Aliased__Macros" ],
    [ "HAL SPI Aliased Macros maintained for legacy purpose", "group__HAL__SPI__Aliased__Macros.html", "group__HAL__SPI__Aliased__Macros" ],
    [ "HAL UART Aliased Macros maintained for legacy purpose", "group__HAL__UART__Aliased__Macros.html", "group__HAL__UART__Aliased__Macros" ],
    [ "HAL USART Aliased Macros maintained for legacy purpose", "group__HAL__USART__Aliased__Macros.html", "group__HAL__USART__Aliased__Macros" ],
    [ "HAL USB Aliased Macros maintained for legacy purpose", "group__HAL__USB__Aliased__Macros.html", "group__HAL__USB__Aliased__Macros" ],
    [ "HAL TIM Aliased Macros maintained for legacy purpose", "group__HAL__TIM__Aliased__Macros.html", "group__HAL__TIM__Aliased__Macros" ],
    [ "HAL ETH Aliased Macros maintained for legacy purpose", "group__HAL__ETH__Aliased__Macros.html", "group__HAL__ETH__Aliased__Macros" ],
    [ "HAL LTDC Aliased Macros maintained for legacy purpose", "group__HAL__LTDC__Aliased__Macros.html", "group__HAL__LTDC__Aliased__Macros" ],
    [ "HAL SAI Aliased Macros maintained for legacy purpose", "group__HAL__SAI__Aliased__Macros.html", "group__HAL__SAI__Aliased__Macros" ],
    [ "HAL SPDIFRX Aliased Macros maintained for legacy purpose", "group__HAL__SPDIFRX__Aliased__Macros.html", null ],
    [ "HAL HRTIM Aliased Functions maintained for legacy purpose", "group__HAL__HRTIM__Aliased__Functions.html", null ],
    [ "HAL QSPI Aliased Macros maintained for legacy purpose", "group__HAL__QSPI__Aliased__Macros.html", null ],
    [ "HAL PPP Aliased Macros maintained for legacy purpose", "group__HAL__PPP__Aliased__Macros.html", null ],
    [ "CMSIS", "group__CMSIS.html", "group__CMSIS" ],
    [ "Learning Core", "group__Machine.html", "group__Machine" ],
    [ "for Smart Mobile Devices", "group__Sensors.html", "group__Sensors" ],
    [ "CMSIS_Device", "group__CMSIS__Device.html", "group__CMSIS__Device" ],
    [ "STM32WLxx_HAL_Driver", "group__STM32WLxx__HAL__Driver.html", "group__STM32WLxx__HAL__Driver" ],
    [ "STM32WLxx_LL_Driver", "group__STM32WLxx__LL__Driver.html", "group__STM32WLxx__LL__Driver" ],
    [ "MOTION APPLICATIONS", "group__MOTION__APPLICATIONS.html", "group__MOTION__APPLICATIONS" ],
    [ "MIDDLEWARES", "group__MIDDLEWARES.html", "group__MIDDLEWARES" ]
];