var searchData=
[
  ['o_20setting_20in_20standby_20shutdown_20mode_0',['GPIO bit number for I/O setting in standby/shutdown mode',['../group__PWREx__GPIO__Bit__Number.html',1,'']]],
  ['of_20life_1',['Monitoring of supply voltage for radio operating level (radio End Of Life)',['../group__PWR__EC__EOL__OPERATING__MODES.html',1,'']]],
  ['of_20stop_20bits_2',['UART Number of Stop Bits',['../group__UART__Stop__Bits.html',1,'']]],
  ['of_20supply_20voltage_20for_20radio_20operating_20level_20radio_20end_20of_20life_3',['Monitoring of supply voltage for radio operating level (radio End Of Life)',['../group__PWR__EC__EOL__OPERATING__MODES.html',1,'']]],
  ['of_20view_4',['I2C Transfer Direction Master Point of View',['../group__I2C__XFERDIRECTION.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_5',['TIM OSSI OffState Selection for Idle mode state',['../group__TIM__OSSI__Off__State__Selection__for__Idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_6',['TIM OSSR OffState Selection for Run mode state',['../group__TIM__OSSR__Off__State__Selection__for__Run__mode__state.html',1,'']]],
  ['on_20gpio_7',['Fast-mode Plus on GPIO',['../group__SYSCFG__FastModePlus__GPIO.html',1,'']]],
  ['on_20rdp_20level_20type_8',['FLASH Option Bytes PCROP On RDP Level Type',['../group__FLASH__OB__PCROP__RDP.html',1,'']]],
  ['on_20rx_20error_9',['UART Advanced Feature DMA Disable On Rx Error',['../group__UART__DMA__Disable__on__Rx__Error.html',1,'']]],
  ['on_20shutdown_10',['FLASH Option Bytes User Reset On Shutdown',['../group__FLASH__OB__USER__nRST__SHUTDOWN.html',1,'']]],
  ['on_20standby_11',['On Standby',['../group__FLASH__OB__USER__IWDG__STANDBY.html',1,'FLASH Option Bytes User IWDG Mode On Standby'],['../group__FLASH__OB__USER__nRST__STANDBY.html',1,'FLASH Option Bytes User Reset On Standby']]],
  ['on_20stop_12',['On Stop',['../group__FLASH__OB__USER__IWDG__STOP.html',1,'FLASH Option Bytes User IWDG Mode On Stop'],['../group__FLASH__OB__USER__nRST__STOP.html',1,'FLASH Option Bytes User Reset On Stop']]],
  ['on_20tamper_20detection_20definitions_13',['RTCEx Tamper TimeStamp On Tamper Detection Definitions',['../group__RTCEx__Tamper__TimeStampOnTamperDetection.html',1,'']]],
  ['one_20bit_20sampling_20method_14',['UART One Bit Sampling Method',['../group__UART__OneBit__Sampling.html',1,'']]],
  ['one_20pulse_20functions_15',['One Pulse functions',['../group__TIMEx__Exported__Functions__Group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group__TIM__Exported__Functions__Group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_16',['TIM One Pulse Mode',['../group__TIM__One__Pulse__Mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_17',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group__HAL__OPAMP__Aliased__Defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_18',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group__HAL__OPAMP__Aliased__Macros.html',1,'']]],
  ['operating_20level_20radio_20end_20of_20life_19',['Monitoring of supply voltage for radio operating level (radio End Of Life)',['../group__PWR__EC__EOL__OPERATING__MODES.html',1,'']]],
  ['operating_20modes_20',['SMPS Step down converter operating modes',['../group__PWR__EC__SMPS__OPERATING__MODES.html',1,'']]],
  ['operation_20functions_21',['operation functions',['../group__I2C__Exported__Functions__Group2.html',1,'Input and Output operation functions'],['../group__EXTI__Exported__Functions__Group2.html',1,'IO operation functions'],['../group__GPIO__Exported__Functions__Group2.html',1,'IO operation functions'],['../group__UART__Exported__Functions__Group2.html',1,'IO operation functions']]],
  ['option_20bit_22',['option bit',['../group__FLASH__OB__USER__BOOT__LOCK.html',1,'FLASH Option Bytes CPU1 Boot Lock option bit'],['../group__FLASH__OB__USER__nBOOT0.html',1,'FLASH Option Bytes User nBOOT0 option bit']]],
  ['option_20bytes_20cpu1_20boot_20lock_20option_20bit_23',['FLASH Option Bytes CPU1 Boot Lock option bit',['../group__FLASH__OB__USER__BOOT__LOCK.html',1,'']]],
  ['option_20bytes_20pcrop_20on_20rdp_20level_20type_24',['FLASH Option Bytes PCROP On RDP Level Type',['../group__FLASH__OB__PCROP__RDP.html',1,'']]],
  ['option_20bytes_20read_20protection_25',['FLASH Option Bytes Read Protection',['../group__FLASH__OB__READ__PROTECTION.html',1,'']]],
  ['option_20bytes_20sram1_20and_20sram2_20erase_20when_20system_20reset_26',['FLASH Option Bytes SRAM1 and SRAM2 erase when system reset',['../group__FLASH__OB__USER__SRAM__RST.html',1,'']]],
  ['option_20bytes_20sram2_20parity_20check_27',['FLASH Option Bytes SRAM2 parity check',['../group__FLASH__OB__USER__SRAM2__PE.html',1,'']]],
  ['option_20bytes_20type_28',['FLASH Option Bytes Type',['../group__FLASH__OB__TYPE.html',1,'']]],
  ['option_20bytes_20user_20boot1_20type_29',['FLASH Option Bytes User BOOT1 Type',['../group__FLASH__OB__USER__nBOOT1.html',1,'']]],
  ['option_20bytes_20user_20bor_20level_30',['FLASH Option Bytes User BOR Level',['../group__FLASH__OB__USER__BOR__LEVEL.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20standby_31',['FLASH Option Bytes User IWDG Mode On Standby',['../group__FLASH__OB__USER__IWDG__STANDBY.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20mode_20on_20stop_32',['FLASH Option Bytes User IWDG Mode On Stop',['../group__FLASH__OB__USER__IWDG__STOP.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20type_33',['FLASH Option Bytes User IWDG Type',['../group__FLASH__OB__USER__IWDG__SW.html',1,'']]],
  ['option_20bytes_20user_20nboot0_20option_20bit_34',['FLASH Option Bytes User nBOOT0 option bit',['../group__FLASH__OB__USER__nBOOT0.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20shutdown_35',['FLASH Option Bytes User Reset On Shutdown',['../group__FLASH__OB__USER__nRST__SHUTDOWN.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20standby_36',['FLASH Option Bytes User Reset On Standby',['../group__FLASH__OB__USER__nRST__STANDBY.html',1,'']]],
  ['option_20bytes_20user_20reset_20on_20stop_37',['FLASH Option Bytes User Reset On Stop',['../group__FLASH__OB__USER__nRST__STOP.html',1,'']]],
  ['option_20bytes_20user_20software_20boot0_38',['FLASH Option Bytes User Software BOOT0',['../group__FLASH__OB__USER__nSWBOOT0.html',1,'']]],
  ['option_20bytes_20user_20type_39',['FLASH Option Bytes User Type',['../group__FLASH__OB__USER__TYPE.html',1,'']]],
  ['option_20bytes_20user_20wwdg_20type_40',['FLASH Option Bytes User WWDG Type',['../group__FLASH__OB__USER__WWDG__SW.html',1,'']]],
  ['options_41',['I2C Sequential Transfer Options',['../group__I2C__XFEROPTIONS.html',1,'']]],
  ['or_203_42',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group__TIM__Group__Channel5.html',1,'']]],
  ['or_20disabled_20status_43',['or Disabled Status',['../group__RCC__AHB1__Peripheral__Clock__Enable__Disable__Status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__AHB1__Clock__Sleep__Enable__Disable__Status.html',1,'AHB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group__RCC__AHB2__Clock__Enable__Disable__Status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__AHB2__Clock__Sleep__Enable__Disable__Status.html',1,'AHB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group__RCC__AHB3__Clock__Enable__Disable__Status.html',1,'AHB3 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__AHB3__Clock__Sleep__Enable__Disable__Status.html',1,'AHB3 Peripheral Clock Sleep Enabled or Disabled Status'],['../group__RCC__APB1__Clock__Enable__Disable__Status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__APB1__Clock__Sleep__Enable__Disable__Status.html',1,'APB1 Peripheral Clock Sleep Enabled or Disabled Status'],['../group__RCC__APB2__Clock__Enable__Disable__Status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__APB2__Clock__Sleep__Enable__Disable__Status.html',1,'APB2 Peripheral Clock Sleep Enabled or Disabled Status'],['../group__RCC__APB3__Clock__Enable__Disable__Status.html',1,'APB3 Peripheral Clock Enabled or Disabled Status'],['../group__RCC__APB3__Clock__Sleep__Enable__Disable__Status.html',1,'APB3 Peripheral Clock Sleep Enabled or Disabled Status']]],
  ['or_20not_20default_20init_20value_20is_20used_44',['Indicates whether or not default init value is used',['../group__CRC__Default__InitValue__Use.html',1,'']]],
  ['or_20not_20default_20polynomial_20is_20used_45',['Indicates whether or not default polynomial is used',['../group__CRC__Default__Polynomial.html',1,'']]],
  ['or_20output_20data_20format_20for_20date_20year_20month_20weekday_20and_20time_20hours_20minutes_20seconds_46',['RTC input or output data format for date (Year, Month, Weekday) and time (Hours, Minutes, Seconds).',['../group__RTC__Input__parameter__format__definitions.html',1,'']]],
  ['or_20stop_20mode_47',['I2C Start or Stop Mode',['../group__I2C__START__STOP__MODE.html',1,'']]],
  ['oscillator_20type_48',['Oscillator Type',['../group__RCC__Oscillator__Type.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_49',['TIM OSSI OffState Selection for Idle mode state',['../group__TIM__OSSI__Off__State__Selection__for__Idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_50',['TIM OSSR OffState Selection for Run mode state',['../group__TIM__OSSR__Off__State__Selection__for__Run__mode__state.html',1,'']]],
  ['out_51',['OUT',['../group__RTC__Output__PullUp__ALARM__OUT.html',1,'RTC Output Pull-Up ALARM OUT'],['../group__RTC__Output__Type__ALARM__OUT.html',1,'RTC Output Type ALARM OUT']]],
  ['out_20remap_52',['RTC Output ALARM OUT Remap',['../group__RTC__Output__ALARM__OUT__Remap.html',1,'']]],
  ['out_20value_53',['UART polling-based communications time-out value',['../group__UART__TimeOut__Value.html',1,'']]],
  ['output_54',['output',['../group__LSM6DSOX__Data.html',1,'']]],
  ['output_55',['PLL Clock Output',['../group__RCC__PLL__Clock__Output.html',1,'']]],
  ['output_20alarm_20out_20remap_56',['RTC Output ALARM OUT Remap',['../group__RTC__Output__ALARM__OUT__Remap.html',1,'']]],
  ['output_20compare_20and_20pwm_20modes_57',['TIM Output Compare and PWM Modes',['../group__TIM__Output__Compare__and__PWM__modes.html',1,'']]],
  ['output_20compare_20functions_58',['Output Compare functions',['../group__TIMEx__Exported__Functions__Group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group__TIM__Exported__Functions__Group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_59',['Output Compare Idle State',['../group__TIM__Output__Compare__N__Idle__State.html',1,'TIM Complementary Output Compare Idle State'],['../group__TIM__Output__Compare__Idle__State.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_60',['Output Compare Polarity',['../group__TIM__Output__Compare__N__Polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group__TIM__Output__Compare__Polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_61',['Output Compare State',['../group__TIM__Output__Compare__N__State.html',1,'TIM Complementary Output Compare State'],['../group__TIM__Output__Compare__State.html',1,'TIM Output Compare State']]],
  ['output_20data_20format_20for_20date_20year_20month_20weekday_20and_20time_20hours_20minutes_20seconds_62',['RTC input or output data format for date (Year, Month, Weekday) and time (Hours, Minutes, Seconds).',['../group__RTC__Input__parameter__format__definitions.html',1,'']]],
  ['output_20data_20inversion_20modes_63',['Output Data Inversion Modes',['../group__CRCEx__Output__Data__Inversion.html',1,'']]],
  ['output_20enable_64',['TIM Automatic Output Enable',['../group__TIM__AOE__Bit__Set__Reset.html',1,'']]],
  ['output_20fast_20state_65',['TIM Output Fast State',['../group__TIM__Output__Fast__State.html',1,'']]],
  ['output_20operation_20functions_66',['Input and Output operation functions',['../group__I2C__Exported__Functions__Group2.html',1,'']]],
  ['output_20polarity_20definitions_67',['RTC Output Polarity Definitions',['../group__RTC__Output__Polarity__Definitions.html',1,'']]],
  ['output_20pull_20up_20alarm_20out_68',['RTC Output Pull-Up ALARM OUT',['../group__RTC__Output__PullUp__ALARM__OUT.html',1,'']]],
  ['output_20selection_20definition_69',['RTCEx Output Selection Definition',['../group__RTCEx__Output__selection__Definitions.html',1,'']]],
  ['output_20selection_20definitions_70',['RTCEx Calib Output selection Definitions',['../group__RTCEx__Calib__Output__selection__Definitions.html',1,'']]],
  ['output_20type_20alarm_20out_71',['RTC Output Type ALARM OUT',['../group__RTC__Output__Type__ALARM__OUT.html',1,'']]],
  ['over_20sampling_72',['UART Over Sampling',['../group__UART__Over__Sampling.html',1,'']]],
  ['overrun_20disable_73',['UART Advanced Feature Overrun Disable',['../group__UART__Overrun__Disable.html',1,'']]],
  ['own_20address2_20masks_74',['I2C Own Address2 Masks',['../group__I2C__OWN__ADDRESS2__MASKS.html',1,'']]]
];
