var group__RTCEx__Exported__Constants =
[
    [ "RTCEx Time Stamp Edges definition", "group__RTCEx__Time__Stamp__Edges__definitions.html", "group__RTCEx__Time__Stamp__Edges__definitions" ],
    [ "RTCEx TimeStamp Pin Selection", "group__RTCEx__TimeStamp__Pin__Selections.html", "group__RTCEx__TimeStamp__Pin__Selections" ],
    [ "RTCEx Wakeup Timer Definitions", "group__RTCEx__Wakeup__Timer__Definitions.html", "group__RTCEx__Wakeup__Timer__Definitions" ],
    [ "RTCEx Smooth calib period Definitions", "group__RTCEx__Smooth__calib__period__Definitions.html", "group__RTCEx__Smooth__calib__period__Definitions" ],
    [ "RTCEx Smooth calib Plus pulses Definitions", "group__RTCEx__Smooth__calib__Plus__pulses__Definitions.html", "group__RTCEx__Smooth__calib__Plus__pulses__Definitions" ],
    [ "RTCEx Smooth calib Low Power Definitions", "group__RTCEx__Smooth__calib__low__power__Definitions.html", "group__RTCEx__Smooth__calib__low__power__Definitions" ],
    [ "RTCEx Calib Output selection Definitions", "group__RTCEx__Calib__Output__selection__Definitions.html", "group__RTCEx__Calib__Output__selection__Definitions" ],
    [ "RTCEx Add 1 Second Parameter Definitions", "group__RTCEx__Add__1__Second__Parameter__Definition.html", "group__RTCEx__Add__1__Second__Parameter__Definition" ],
    [ "RTCEx Tamper Pins Definition", "group__RTCEx__Tamper__Pins.html", "group__RTCEx__Tamper__Pins" ],
    [ "RTCEx Internal Tamper Pins Definition", "group__RTCEx__Internal__Tamper__Pins.html", "group__RTCEx__Internal__Tamper__Pins" ],
    [ "RTCEx Tamper Trigger", "group__RTCEx__Tamper__Trigger.html", "group__RTCEx__Tamper__Trigger" ],
    [ "RTCEx Tamper MaskFlag", "group__RTCEx__Tamper__MaskFlag.html", "group__RTCEx__Tamper__MaskFlag" ],
    [ "RTCEx Tamper EraseBackUp", "group__RTCEx__Tamper__EraseBackUp.html", "group__RTCEx__Tamper__EraseBackUp" ],
    [ "RTCEx Tamper Filter", "group__RTCEx__Tamper__Filter.html", "group__RTCEx__Tamper__Filter" ],
    [ "RTCEx Tamper Sampling Frequencies", "group__RTCEx__Tamper__Sampling__Frequencies.html", "group__RTCEx__Tamper__Sampling__Frequencies" ],
    [ "RTCEx Tamper Pin Precharge Duration", "group__RTCEx__Tamper__Pin__Precharge__Duration.html", "group__RTCEx__Tamper__Pin__Precharge__Duration" ],
    [ "RTCEx Tamper Pull UP", "group__RTCEx__Tamper__Pull__UP.html", "group__RTCEx__Tamper__Pull__UP" ],
    [ "RTCEx Tamper TimeStamp On Tamper Detection Definitions", "group__RTCEx__Tamper__TimeStampOnTamperDetection.html", "group__RTCEx__Tamper__TimeStampOnTamperDetection" ],
    [ "RTCEx Internal Tamper Interrupt", "group__RTCEx__Internal__Tamper__Interrupt.html", "group__RTCEx__Internal__Tamper__Interrupt" ],
    [ "RTCEx Flags", "group__RTCEx__Flags.html", "group__RTCEx__Flags" ],
    [ "RTCEx Monotonic Counter Instance Definition", "group__RTCEx__MonotonicCounter__Instance.html", "group__RTCEx__MonotonicCounter__Instance" ],
    [ "RTCEx Backup Registers Definition", "group__RTCEx__Backup__Registers.html", "group__RTCEx__Backup__Registers" ],
    [ "RTC Binary Mode (32-bit free-running counter configuration).", "group__RTCEx__Binary__Mode.html", "group__RTCEx__Binary__Mode" ],
    [ "If Binary mode is RTC_BINARY_MIX, the BCD calendar second is incremented using the SSR Least Significant Bits.", "group__RTCEx__Binary__mix__BCDU.html", "group__RTCEx__Binary__mix__BCDU" ],
    [ "RTC Alarm Sub Seconds with binary mode Masks Definitions", "group__RTCEx__Alarm__Sub__Seconds__binary__Masks__Definitions.html", "group__RTCEx__Alarm__Sub__Seconds__binary__Masks__Definitions" ],
    [ "RTC Alarm Sub Seconds with binary mode auto clear Definitions", "group__RTCEx__Alarm__Sub__Seconds__binary__Clear__Definitions.html", "group__RTCEx__Alarm__Sub__Seconds__binary__Clear__Definitions" ]
];