var group__FLASH__FLAGS =
[
    [ "FLASH Interrupts Definition", "group__FLASH__INTERRUPT__DEFINITION.html", "group__FLASH__INTERRUPT__DEFINITION" ],
    [ "FLASH Error", "group__FLASH__ERROR.html", "group__FLASH__ERROR" ],
    [ "FLASH Erase Type", "group__FLASH__TYPE__ERASE.html", "group__FLASH__TYPE__ERASE" ],
    [ "FLASH Program Type", "group__FLASH__TYPE__PROGRAM.html", "group__FLASH__TYPE__PROGRAM" ],
    [ "FLASH Option Bytes Type", "group__FLASH__OB__TYPE.html", "group__FLASH__OB__TYPE" ],
    [ "FLASH WRP Area", "group__FLASH__OB__WRP__AREA.html", "group__FLASH__OB__WRP__AREA" ],
    [ "FLASH Option Bytes Read Protection", "group__FLASH__OB__READ__PROTECTION.html", "group__FLASH__OB__READ__PROTECTION" ],
    [ "FLASH Option Bytes User Type", "group__FLASH__OB__USER__TYPE.html", "group__FLASH__OB__USER__TYPE" ],
    [ "FLASH Option Bytes User BOR Level", "group__FLASH__OB__USER__BOR__LEVEL.html", "group__FLASH__OB__USER__BOR__LEVEL" ],
    [ "FLASH Option Bytes User Reset On Stop", "group__FLASH__OB__USER__nRST__STOP.html", "group__FLASH__OB__USER__nRST__STOP" ],
    [ "FLASH Option Bytes User Reset On Standby", "group__FLASH__OB__USER__nRST__STANDBY.html", "group__FLASH__OB__USER__nRST__STANDBY" ],
    [ "FLASH Option Bytes User Reset On Shutdown", "group__FLASH__OB__USER__nRST__SHUTDOWN.html", "group__FLASH__OB__USER__nRST__SHUTDOWN" ],
    [ "FLASH Option Bytes User IWDG Type", "group__FLASH__OB__USER__IWDG__SW.html", "group__FLASH__OB__USER__IWDG__SW" ],
    [ "FLASH Option Bytes User IWDG Mode On Stop", "group__FLASH__OB__USER__IWDG__STOP.html", "group__FLASH__OB__USER__IWDG__STOP" ],
    [ "FLASH Option Bytes User IWDG Mode On Standby", "group__FLASH__OB__USER__IWDG__STANDBY.html", "group__FLASH__OB__USER__IWDG__STANDBY" ],
    [ "FLASH Option Bytes User WWDG Type", "group__FLASH__OB__USER__WWDG__SW.html", "group__FLASH__OB__USER__WWDG__SW" ],
    [ "FLASH Option Bytes SRAM2 parity check", "group__FLASH__OB__USER__SRAM2__PE.html", "group__FLASH__OB__USER__SRAM2__PE" ],
    [ "FLASH Option Bytes SRAM1 and SRAM2 erase when system reset", "group__FLASH__OB__USER__SRAM__RST.html", "group__FLASH__OB__USER__SRAM__RST" ],
    [ "FLASH Option Bytes User BOOT1 Type", "group__FLASH__OB__USER__nBOOT1.html", "group__FLASH__OB__USER__nBOOT1" ],
    [ "FLASH Option Bytes User Software BOOT0", "group__FLASH__OB__USER__nSWBOOT0.html", "group__FLASH__OB__USER__nSWBOOT0" ],
    [ "FLASH Option Bytes User nBOOT0 option bit", "group__FLASH__OB__USER__nBOOT0.html", "group__FLASH__OB__USER__nBOOT0" ],
    [ "FLASH Option Bytes CPU1 Boot Lock option bit", "group__FLASH__OB__USER__BOOT__LOCK.html", "group__FLASH__OB__USER__BOOT__LOCK" ],
    [ "FLASH PCROP ZONE", "group__FLASH__OB__PCROP__ZONE.html", "group__FLASH__OB__PCROP__ZONE" ],
    [ "FLASH Option Bytes PCROP On RDP Level Type", "group__FLASH__OB__PCROP__RDP.html", "group__FLASH__OB__PCROP__RDP" ],
    [ "FLASH_FLAG_ALL_ERRORS", "group__FLASH__FLAGS.html#gaeaca88895411c945120f4e44bfbbc758", null ],
    [ "FLASH_FLAG_BSY", "group__FLASH__FLAGS.html#gad3bc368f954ad7744deda3315da2fff7", null ],
    [ "FLASH_FLAG_CFGBSY", "group__FLASH__FLAGS.html#gaa31cc1631af91a80ea3416de835a7e12", null ],
    [ "FLASH_FLAG_ECCC", "group__FLASH__FLAGS.html#ga1cbecfb0d93e7ae15054d3a561e7b6ef", null ],
    [ "FLASH_FLAG_ECCD", "group__FLASH__FLAGS.html#ga8de3284440e43c3818efe15bd61ef284", null ],
    [ "FLASH_FLAG_ECCR_ERRORS", "group__FLASH__FLAGS.html#gabe226a49ae06fe4da74bebc935e56b0c", null ],
    [ "FLASH_FLAG_EOP", "group__FLASH__FLAGS.html#gaf043ba4d8f837350bfc7754a99fae5a9", null ],
    [ "FLASH_FLAG_FASTERR", "group__FLASH__FLAGS.html#gad8f375a352a04668679609fe25eb1b03", null ],
    [ "FLASH_FLAG_MISERR", "group__FLASH__FLAGS.html#ga706480b4a9e153c0affd52bb239925bc", null ],
    [ "FLASH_FLAG_OPERR", "group__FLASH__FLAGS.html#gad8a96ceda91fcf0d1299da933b5816f1", null ],
    [ "FLASH_FLAG_OPTNV", "group__FLASH__FLAGS.html#ga97c7ff39e962a555558b24bfaebb8e94", null ],
    [ "FLASH_FLAG_OPTVERR", "group__FLASH__FLAGS.html#gacb2c4c991a260c3f110cd8c72f302864", null ],
    [ "FLASH_FLAG_PESD", "group__FLASH__FLAGS.html#ga8ee0a2950015433fcbcb6fc37d1981a8", null ],
    [ "FLASH_FLAG_PGAERR", "group__FLASH__FLAGS.html#ga2c3f4dbea065f8ea2987eada4dab30bd", null ],
    [ "FLASH_FLAG_PGSERR", "group__FLASH__FLAGS.html#ga25b80c716320e667162846da8be09b68", null ],
    [ "FLASH_FLAG_PROGERR", "group__FLASH__FLAGS.html#ga16feb349d40137ba1d00bc44937fcd33", null ],
    [ "FLASH_FLAG_RDERR", "group__FLASH__FLAGS.html#ga0d1faec4c7bcca54d543ff3cd8983d3b", null ],
    [ "FLASH_FLAG_SIZERR", "group__FLASH__FLAGS.html#gac20909664e371d2ca0436a055393f9c4", null ],
    [ "FLASH_FLAG_SR_ERRORS", "group__FLASH__FLAGS.html#gabe182c06cbba0f4514932f295e16bbe7", null ],
    [ "FLASH_FLAG_WRPERR", "group__FLASH__FLAGS.html#ga6abf64f916992585899369166db3f266", null ]
];