var group__UART__Exported__Constants =
[
    [ "UART State Code Definition", "group__UART__State__Definition.html", "group__UART__State__Definition" ],
    [ "UART Error Definition", "group__UART__Error__Definition.html", "group__UART__Error__Definition" ],
    [ "UART Number of Stop Bits", "group__UART__Stop__Bits.html", "group__UART__Stop__Bits" ],
    [ "UART Parity", "group__UART__Parity.html", "group__UART__Parity" ],
    [ "UART Hardware Flow Control", "group__UART__Hardware__Flow__Control.html", "group__UART__Hardware__Flow__Control" ],
    [ "UART Transfer Mode", "group__UART__Mode.html", "group__UART__Mode" ],
    [ "UART State", "group__UART__State.html", "group__UART__State" ],
    [ "UART Over Sampling", "group__UART__Over__Sampling.html", "group__UART__Over__Sampling" ],
    [ "UART One Bit Sampling Method", "group__UART__OneBit__Sampling.html", "group__UART__OneBit__Sampling" ],
    [ "UART Clock Prescaler", "group__UART__ClockPrescaler.html", "group__UART__ClockPrescaler" ],
    [ "UART Advanced Feature AutoBaud Rate Mode", "group__UART__AutoBaud__Rate__Mode.html", "group__UART__AutoBaud__Rate__Mode" ],
    [ "UART Receiver Timeout", "group__UART__Receiver__Timeout.html", "group__UART__Receiver__Timeout" ],
    [ "UART Local Interconnection Network mode", "group__UART__LIN.html", "group__UART__LIN" ],
    [ "UART LIN Break Detection", "group__UART__LIN__Break__Detection.html", "group__UART__LIN__Break__Detection" ],
    [ "UART DMA Tx", "group__UART__DMA__Tx.html", "group__UART__DMA__Tx" ],
    [ "UART DMA Rx", "group__UART__DMA__Rx.html", "group__UART__DMA__Rx" ],
    [ "UART Half Duplex Selection", "group__UART__Half__Duplex__Selection.html", "group__UART__Half__Duplex__Selection" ],
    [ "UART WakeUp Methods", "group__UART__WakeUp__Methods.html", "group__UART__WakeUp__Methods" ],
    [ "UART Request Parameters", "group__UART__Request__Parameters.html", "group__UART__Request__Parameters" ],
    [ "UART Advanced Feature Initialization Type", "group__UART__Advanced__Features__Initialization__Type.html", "group__UART__Advanced__Features__Initialization__Type" ],
    [ "UART Advanced Feature TX Pin Active Level Inversion", "group__UART__Tx__Inv.html", "group__UART__Tx__Inv" ],
    [ "UART Advanced Feature RX Pin Active Level Inversion", "group__UART__Rx__Inv.html", "group__UART__Rx__Inv" ],
    [ "UART Advanced Feature Binary Data Inversion", "group__UART__Data__Inv.html", "group__UART__Data__Inv" ],
    [ "UART Advanced Feature RX TX Pins Swap", "group__UART__Rx__Tx__Swap.html", "group__UART__Rx__Tx__Swap" ],
    [ "UART Advanced Feature Overrun Disable", "group__UART__Overrun__Disable.html", "group__UART__Overrun__Disable" ],
    [ "UART Advanced Feature Auto BaudRate Enable", "group__UART__AutoBaudRate__Enable.html", "group__UART__AutoBaudRate__Enable" ],
    [ "UART Advanced Feature DMA Disable On Rx Error", "group__UART__DMA__Disable__on__Rx__Error.html", "group__UART__DMA__Disable__on__Rx__Error" ],
    [ "UART Advanced Feature MSB First", "group__UART__MSB__First.html", "group__UART__MSB__First" ],
    [ "UART Advanced Feature Stop Mode Enable", "group__UART__Stop__Mode__Enable.html", "group__UART__Stop__Mode__Enable" ],
    [ "UART Advanced Feature Mute Mode Enable", "group__UART__Mute__Mode.html", "group__UART__Mute__Mode" ],
    [ "UART Address-matching LSB Position In CR2 Register", "group__UART__CR2__ADDRESS__LSB__POS.html", "group__UART__CR2__ADDRESS__LSB__POS" ],
    [ "UART WakeUp From Stop Selection", "group__UART__WakeUp__from__Stop__Selection.html", "group__UART__WakeUp__from__Stop__Selection" ],
    [ "UART DriverEnable Polarity", "group__UART__DriverEnable__Polarity.html", "group__UART__DriverEnable__Polarity" ],
    [ "UART Driver Enable Assertion Time LSB Position In CR1 Register", "group__UART__CR1__DEAT__ADDRESS__LSB__POS.html", "group__UART__CR1__DEAT__ADDRESS__LSB__POS" ],
    [ "UART Driver Enable DeAssertion Time LSB Position In CR1 Register", "group__UART__CR1__DEDT__ADDRESS__LSB__POS.html", "group__UART__CR1__DEDT__ADDRESS__LSB__POS" ],
    [ "UART Interruptions Flag Mask", "group__UART__Interruption__Mask.html", "group__UART__Interruption__Mask" ],
    [ "UART polling-based communications time-out value", "group__UART__TimeOut__Value.html", "group__UART__TimeOut__Value" ],
    [ "UART Status Flags", "group__UART__Flags.html", "group__UART__Flags" ],
    [ "UART Interrupts Definition", "group__UART__Interrupt__definition.html", "group__UART__Interrupt__definition" ],
    [ "UART Interruption Clear Flags", "group__UART__IT__CLEAR__Flags.html", "group__UART__IT__CLEAR__Flags" ],
    [ "UART Reception type values", "group__UART__RECEPTION__TYPE__Values.html", "group__UART__RECEPTION__TYPE__Values" ]
];